### ISSUE TITLE
Remove UI which will not soon be backed by API?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/hubmap-data-portal#161]
As we start to fill in the API I think it may become important to clearly distinguish between things which are mockups, and things which have real API support behind them. What I really want to avoid is a situation where either the developers or the POs lose track of what is real and just waiting for data in the backend, and what is fake.

To do this, I propose removing all the charts from the homepage, and as we have an API which can support it, reintroduce them.

cc: @sushma-ananda, @mruffalo : Would you be on-board with this? Or would you propose a different solution?

**Comment by sushmaanandakoju** [comment]
@mccalluc Yes it is good you are looking API supported charts. But I think we could have charts that are better filled from mockups : JSON files until APIs are available. So we can modify charts to fill up from mock UIs instead of gettind rid of them altogether. So we can display something until real-data is available. @mruffalo what do you suggest ?

**Comment by mccalluc** [comment]
Making a fresh start in flask-data-portal, and not carrying over any of the old UI for now. Closing.
