### ISSUE TITLE
Serve React app as static content in production

### ISSUE THREAD

**Issue by mruffalo** [hubmapconsortium/hubmap-data-portal#18]
The current "production" architecture serves the React app in a way that's more suited to local development. Use webpack to compile the React app to static Javascript/CSS bundles so we can serve this as static content in production. This will remove the need to run the `reactjs_app` Docker container.

This has a few consequences for the application architecture.
- Currently, the React app "owns" most of the URL namespace, with `/api` and `/admin` routed to the Django app and `/_static` served by `nginx` from the filesystem.
- After this, the Django app will receive the entire URL namespace; the Django REST framework will respond to everything under `/api`, and everything else will have free-form URL mappings. The root URL `/` will render a HTML template similar to [`frontend/public/index.html`](https://github.com/hubmapconsortium/hubmap-data-portal/blob/4262646bdcc26722d074f4924d46e0849f16f903/hubmap/frontend/public/index.html). Static content for both the Django and React apps will be accessible through `/static`.

**Comment by sushma-ananda** [comment]
Thank you Matt. As we discussed I am categorizing the same into following sub-categories:
1) host create-react-app's (CRA) static content in Django/templates
2) host CRA without having to run "npm start"
3) (not part of this issue) be able to host multiple pages in single CRA and should work with 1) and 2) above.
Refer: https://github.com/sushma-ananda/hubmap-dataportal/tree/django-react-bad-2

**Comment by sushma-ananda** [comment]
W.r.t point **2.** from above comment, on further analysis, "react-scripts" package seems to address what a CRA configuration wants in order to build and split into static files. Not a good practice: but it seems [react-scripts](https://github.com/facebook/create-react-app/tree/master/packages/react-scripts) is completely written for CRA, but it looks like these scripts have to be tweaked or just keep fixing one error by another when configuring webpack from scratch. [W.I.P]

**Comment by sushma-ananda** [comment]
W.r.t host CRA without having to run "npm start": it seems [react-scripts](https://github.com/facebook/create-react-app/tree/master/packages/react-scripts) to work well for CRA, in order to build and split into static files. appears like not a good practice since it is not customizable unless forking entire react-scripts package : but it looks like just keep fixing one error by another when configuring webpack from scratch. [W.I.P]

**Comment by sushma-ananda** [comment]
Hi Matt, looks like this moving from CRA is moving from client-side rendering to server-side rendering, if that is the case, we need additional plugins/configuration. Are we moving to server-side rendering ?

**Comment by mruffalo** [comment]
Not at all; we'll continue to use client-side rendering for the foreseeable future. The idea is that the JSX code will be converted to "plain" Javascript files _once_, then those Javascript files will be served from something like `nginx` (directly from the filesystem) or a CDN.

**Comment by sushma-ananda** [comment]
Ohh I see, thanks for clarifying this, sounds great.

**Comment by sushma-ananda** [comment]
Hi @mruffalo , Thanks for docker configuration, and the idea to use Linux. Docker containers are working super cool - almost no-time-to-load/start django/reactjs apps. :whale:
