### ISSUE TITLE
Test login in Cypress with stub

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/hubmap-data-portal#98]
We want to test that webapp behavior after login is correct. I think we want to use some combination of Cypress [stubs](https://docs.cypress.io/api/commands/stub.html) and mocked API responses. (Another approach would be to get a real, limited priv globus user, but depending on live services during tests is usually a bad idea.)

@sushma-ananda : If you have any interest in this, assign yourself, or if not I can try.

**Comment by sushma-ananda** [comment]
@mccalluc Appreciate your initiative to add tests and eslint to this prototype app, thanks so much for your work. Yes adding tests for login is great idea. As we have call in few minutes, it would be good to discuss this, thanks so much for bringing this up.

**Comment by sushma-ananda** [comment]
@mccalluc @mruffalo 
The tests for globus-auth login/logout is added as follows:
1) Stub based login/logout (we don't need django running)
2) Login/logout with Django RESt api (live tests)

could you please test run or take a look at this tests: [auth-tests](https://github.com/hubmapconsortium/hubmap-data-portal/tree/test-globus-login) and let me know if anything ?
Do we want to provide separate Readme for Setting up Cypress and test config ?

**Comment by mccalluc** [comment]
Cool: I just created a PR: #103. (With a PR there's a really good interface for giving feedback line-by-line, and it will run the tests, so we'll all see the same green checkmark, hopefully.) Further comments there.

**Comment by sushma-ananda** [comment]
great! Thanks. I replied to some comments, I am not sure I am implementing all the comments. Please take a look at comments and let me know your thoughts, will be glad to discuss further and then I can incorporate/not as per further consensus. For all the remaining of your comments: I am incorporating them, which I may upload by EOD or tomorrow. However, I have a general comment, it is nice you are doubting and questioning, however, I would ask why someone implemented something, that will probably help us all developers be on same page.

**Comment by sushma-ananda** [comment]
great! Thanks. I replied to some comments, I am not sure I am implementing all the comments. Please take a look at comments and let me know your thoughts, will be glad to discuss further and then I can incorporate/not as per further consensus. For all the remaining of your comments: I am incorporating them, which I may upload by EOD or tomorrow.

**Comment by sushma-ananda** [comment]
great! Thanks. I replied to some comments, I am not sure I am implementing all the comments. Please take a look at comments and let me know your thoughts, will be glad to discuss further and then I can incorporate/not as per further consensus. For all the remaining of your comments: I am incorporating them, which I will upload soon, after I finish working on something else.

**Comment by sushma-ananda** [comment]
I more or less incorporated all of your comments, except few that are not 'outdated' . Please take a look and let me know. Travis build is fine seems fine. presently, I am "skip"ing live auth tests, is there any way we can configure cypress to ignore few tests that require REST api/some additional configurations ?

**Comment by mccalluc** [comment]
> presently, I am "skip"ing live auth tests

I think we really only want tests that can run in every environment. (Possible exception: If we find a bug, and want to write a test of the behavior we'd like to see, that might be a good use for `skip`, until the bug is fixed.) It was good to try exercising more parts of the system, but I think it will be more coherent if we say that Cypress is really only for testing the front end, and we shouldn't test live auth.

**Comment by sushma-ananda** [comment]
Thanks, looking forward to discussion on PR #103 . For the purpose of documenting summary of my findings w.r.t cypress testing for auth for past ~2 days : as per [test-auth-login](https://github.com/hubmapconsortium/hubmap-data-portal/tree/test-globus-login), Cypress route/request methods do not stub redirect requests (Http 303/304). Since clicking on login/logout is a redirect, we do not want to include tests for this. Also as per stand-up discussion, we do not want to have "live" auth tests. So as per this issue's description: having to test live may not be a good idea for development, but might be an idea to consider for testing live in production (as in perhaps a sanity test to test redirect although the urls in production are not cross-domain in production). Cypress is good tool to test react app, with couple of limitations. I also happened to create this [testing scope](https://github.com/hubmapconsortium/hubmap-data-portal/issues/106) for further discussion (since scope of this issue is limited to auth and more questions for better collaboration), going forward. Looking forward to learn/hear more.

**Comment by sushma-ananda** [comment]
@mccalluc Thanks for your initiative to add tests. Please refer: https://github.com/hubmapconsortium/hubmap-data-portal/issues/98#issuecomment-523107515
As per our recent discussion, to summarize: 
1) remove fixtures for login/logout 
2) revert responseTimeout to default setting 
3) we do **not** intend to run live tests as per findings above. 
4) as discussed, there are two open questions on https://github.com/hubmapconsortium/hubmap-data-portal/pull/103 
5) going forward, we would be avoiding _effort duplication and have more communication_ as part of process. 
6) Since you are taking lead on auth-tests, please take a look at #103 and let me know if you prefer to merge.
7) Please do let me know in case if I missed anything/if you feel something modified in this summary.
